image: centos:centos7

before_script:
  - yum install -y -t https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  - yum -y -t install python36 python34-pip python36-devel unzip mysql-devel gcc git openldap-devel
  - pip3 install pip --upgrade
  - pip install virtualenv --upgrade
  - virtualenv -p python3.6 /tmp/.virtualenv
  - source /tmp/.virtualenv/bin/activate
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
  - pip install pycco
  - pip install django_coverage_plugin

test_and_coverage:
  stage: test
  script:
    - echo "TEMPLATES[0]['OPTIONS']['debug'] = True" > config_local.py
    - echo "DEBUG = True" >> config_local.py
    - python manage.py collectstatic --noinput
    - coverage run --source . manage.py test -v3
    - coverage report --fail-under=70
    - coverage html
  artifacts:
    paths:
      - htmlcov/

pycco:
  stage: test
  script:
    - /bin/true
    - find ivatar/ -type f -name "*.py"|grep -v __pycache__|grep -v __init__.py|grep -v /migrations/ | xargs pycco -p -d pycco -i -s
  artifacts:
    paths:
      - pycco/
    expire_in: 14 days

pages:
  before_script:
    - /bin/true
    - /bin/true
  stage: deploy
  dependencies:
    - test_and_coverage
    - pycco
  script:
    - mv htmlcov/ public/
    - mv pycco/ public/
  artifacts:
    paths:
      - public
    expire_in: 14 days
  only:
    - master
